### ISSUE TITLE
Error handling for non found file

### ISSUE THREAD

**Issue by cameronstewart** [njanakiev/folderstats#1]
Hi there,

I have found that the module throws and error - It seems that there is a are a few cases whereby files cant be opened, aren't found...or something else...file is about 10 levels deep

It throws a 
FileNotFoundError: [WinError 3] The system cannot find the path specified: \\LongPath\\filename.pdf'

**Comment by njanakiev** [comment]
Thanks for the issue @cameronstewart! Does this error also appear when you run it as administrator?
Also feel free to add a PR, as I currently cannot test this on Windows.

**Comment by cameronstewart** [comment]
Yes, have tried via Jupyter running as admin and produces the same results.  Also from cmd as admin.

there are a few conditions that it bugs out on

FileNotFoundError: [WinError 3] 
PermissionError: [WinError 5] Access is denied

**Comment by njanakiev** [comment]
Thanks, @cameronstewart! I will add the exception handling in the following days!
