### ISSUE TITLE
Consider using scandir() instead of listdir()

### ISSUE THREAD

**Issue by adrianyorke** [njanakiev/folderstats#12]
Firstly, thanks for this wonderful module.  One improvement suggestion is to use scandir() rather than listdir().

You can read more about scandir() here:
https://www.python.org/dev/peps/pep-0471/

This text is particularly relevant:
"Like listdir, scandir calls the operating system's directory iteration system calls to get the names of the files in the given path, but it's different from listdir in two ways:

1. Instead of returning bare filename strings, it returns lightweight DirEntry objects that hold the filename string and provide simple methods that allow access to the additional data the operating system may have returned.
2. It returns a generator instead of a list, so that scandir acts as a true iterator instead of returning the full list immediately."

**Comment by njanakiev** [comment]
Thanks for the hint @adrianyorke! This was indeed something I had in mind! I've added it to the latest `0.4.0` release.

**Comment by adrianyorke** [comment]
Thank you @njanakiev - great work!
