### ISSUE TITLE
unix: parent of empty sub-folder shows num_files = 0 

### ISSUE THREAD

**Issue by easyas314** [njanakiev/folderstats#15]
Test case:

1. mkdir -p /tmp/mytest/foo/bar
2. ipython
```
In [1]: import folderstats

In [2]: df = folderstats.folderstats('/tmp/mytest',ignore_hidden=True)

In [3]: df
Out[3]:
   id                 path    name extension  size  ... folder num_files depth  parent   uid
0   3  /tmp/mytest/foo/bar     bar      None     0  ...   True         0     2       2  1007
1   2      /tmp/mytest/foo     foo      None    10  ...   True         0     1       1  1007
2   1          /tmp/mytest  mytest      None    35  ...   True         0     0       0  1007

```
Expected result: num_files = 1 for both id=1 and 2

**Comment by easyas314** [comment]
Same result without use of `ignore_hidden=True`.
Folders are just "special" files. So only id=3 has the correct value for num_files and can be removed with a basic os.rmdir() The other ids generate O/S errors for "Directory not empty", so the num_files is not 0.

**Comment by njanakiev** [comment]
Thanks for the issue, @easyas314. I sadly do not agree on this point, although I see your point in terms of the way Linux thinks about it. In this case the focus is on more general data analysis with the file system with a stronger focus on files in the non-Linux sense.

The number of directories could eventually be added as an additional column if there is enough interest as I am certain people would want to differentiate between files and folders. Feel free to add a PR if this is something you definitely want to have and I'll look over it.

On a different note, this would also open up the discussion about `/var/run`, unix sockets and similar "files" which are currently not actively covered nor tested. I will close this issue for now unless more people raise these questions.
