### ISSUE TITLE
Repeating the folderstats method yields duplicated DataFrame

### ISSUE THREAD

**Issue by atallaashraf** [njanakiev/folderstats#2]
When using the following code (repeating the python command), the final df has duplicated files. 

df = folderstats('directory', ignore_hidden=True)
df = folderstats('directory', ignore_hidden=True)

**Comment by arshdeepbal** [comment]
Yes. While using folderstats module in python3, the records are cascaded from all previous runs of folderstats for that specific session i.e. once the folderstats is run, it will provide the dataframe with all the files/directories in that directory, but if we run it another time, the new data is appended to the old data.

To overcome this issue you can make a minor change in the folderstats module and import it : 
**__init__.py :**
In **method folderstats()** edit the below line to make an addition i.e initialise items=list() so as the data is not appended to the previous list : 

idx, items, foldersize, num_files = _recursive_folderstats(
        folderpath,
        hash_name=hash_name,**items=list()**
        ignore_hidden=ignore_hidden,
        verbose=verbose)

Let me know if this helps !

**Comment by Jul75** [comment]
Hello, 
Thanks a lot for this help. 

For me the Alternate Method doesn't give me the good result (less files than exist), but the first one does.

**Comment by th0ger** [comment]
@njanakiev any interest in fixing this? last commit > 1 yr.

**Comment by njanakiev** [comment]
Thanks, Ashraf and Arshdeep for pointing this issue out, this behavior was new to me. It is fixed now.

**Comment by th0ger** [comment]
Confirming fix. Thanks a lot.

**Comment by Jul75** [comment]
Thanks dude !
