### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by oyearunpal** [njanakiev/folderstats#6]
Getting  Permission denied error, Reason is the folder I am trying to access I have no rights on that.

**Comment by oyearunpal** [comment]
Need to add at line 31 
`    if os.access(folderpath,os.R_OK):`

**Comment by njanakiev** [comment]
Thanks, Arun!

**Comment by zeroalphagit** [comment]
Is it possible to add Permission error handling to sub folders or files also? For example I get:

[WinError 5] Access is denied: 'D:/System Volume Information'

This causes the whole script to fail
