### ISSUE TITLE
ValueError: Type names and field names cannot be a keyword: 'False'

### ISSUE THREAD

**Issue by th0ger** [njanakiev/folderstats#8]
When debuging the src i get:
`python -m folderstats .`

`File "/home/\<user>/anaconda3/envs/folderstats/lib/python3.8/collections/__init__.py", line 361, in namedtuple
    raise ValueError('Type names and field names cannot be a '
ValueError: Type names and field names cannot be a keyword: 'False'`

The code breaks in `__main__.py`  at
`for row in df.itertuples(index=False, name=False)`.
According to [pandas itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html), `name` must be a string or `None`, not a boolan.

Fix:
`for row in df.itertuples(index=False, name=None)`.

**Comment by MariuszDe** [comment]
Thank you, It saved me a lot of time.
